# Generated by Django 4.1.2 on 2024-05-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_visible_repository',
            field=models.BooleanField(default=False),
        ),
    ]
