# Generated by Django 4.1.2 on 2024-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_is_visible_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_visible_repository',
        ),
        migrations.AddField(
            model_name='project',
            name='is_visible_repository',
            field=models.BooleanField(default=False),
        ),
    ]
